### PR TITLE
Data Validation for add goals, edit goals, add comm log

### PR DESCRIPTION
**Pull request by omrajpal**

### CODE REVIEW

**Review by Jihong-Bae — APPROVED** [review]

**Review by hraetz — APPROVED** [review]
idk

**Review by abby-winn — APPROVED** [review]
French fries, also called chips, finger chips, fries, or French pommes frites, side dish or snack typically made from deep-fried potatoes that have been cut into various shapes, especially thin strips. Fries are often salted and served with other items.

**Review by brandon-moyer — CHANGES_REQUESTED** [review]
Goals cannot be set for the past, and goalReview should be set for a date after today.

**Review by brandon-moyer — APPROVED** [review]
:(

**Review by NoahRen25 — APPROVED** [review]

**Review by Asingh11771 — APPROVED** [review]
Still needs major fixes, but whatever

**Pull request merged**
