### PR TITLE
Merge branch 'develop' into switchCoachOnCancel

### PR DESCRIPTION
**Pull request by Jihong-Bae**
Issue: cancel button in assign coach doesn't reset entry

PLS GO CHECK THE STUDENTS PAGE ASSIGN COACH

### CODE REVIEW

**Review by NoahRen25 — APPROVED** [review]

**Review by Asingh11771 — APPROVED** [review]
good

**Comment by TortoiseRevenge** [comment]
"See, free nations are peaceful nations. Free nations don't attack each other. Free nations don't develop weapons of mass destruction." - George Dubya Bush

**Review by brandon-moyer — APPROVED** [review]
video gameing

**Review by hraetz — APPROVED** [review]
what

**Pull request closed without merging**
