### PR TITLE
changing goal set date to be 6 months back not 1

### PR DESCRIPTION
**Pull request by omrajpal**

### CODE REVIEW

**Review by TortoiseRevenge — APPROVED** [review]
image

**Review by Jihong-Bae — APPROVED** [review]

**Review by hraetz — APPROVED** [review]
jorg dubya

**Review by Asingh11771 — APPROVED** [review]
looks good

**Review by abby-winn — APPROVED** [review]
"In the realm of coding, failure to create good code is not a mark of defeat, but rather a profound invitation to growth. Embrace the humbling dance with imperfection, for it is within the depths of each flawed line that the seeds of mastery find fertile ground to flourish._" -ChatGPT_

also: 
As of my last update in September 2021, LaCroix is a popular brand of sparkling water known for its wide range of flavors. The ingredients in LaCroix sparkling water are generally simple and limited. The primary components include:

Carbonated Water: The base ingredient of sparkling water, which is water infused with carbon dioxide to create the bubbles.

Natural Flavors: LaCroix uses natural fruit flavors to give its sparkling water its distinct taste. The specific natural flavors can vary depending on the flavor variant (e.g., lemon, lime, grapefruit, etc.).

Citric Acid: This ingredient helps to provide a slightly tart taste and acts as a preservative.

**Review by AlanJSudhan — APPROVED** [review]

**Review by brandon-moyer — APPROVED** [review]

**Pull request merged**
