### PR TITLE
Fix Phone Number Regex for Edit Student Info and added Other Option to Career Cluster

### PR DESCRIPTION
**Pull request by Asingh11771**

### CODE REVIEW

**Review by abby-winn — APPROVED** [review]
“Let me rephrase.” He took a seething step toward me. “When it comes to you… I don’t like to share.” _-Samantha Young, On Dublin Street_

**Review by TortoiseRevenge — APPROVED** [review]

**Review by hraetz — APPROVED** [review]
needs to display error on text fields but good
"In the annals of time, the alpha male emerges as a titan, an indomitable force of nature whose mere presence commands respect and evokes a primal sense of awe. He is a living embodiment of strength, both physical and spiritual, a symphony of resilience and audacity that defies the constraints of ordinary existence. With unwavering determination, he surges forward, overcoming insurmountable odds, conquering the unconquerable, and shattering the limitations of what is considered possible. His spirit blazes like a supernova, illuminating the darkest corners of doubt and igniting a wildfire of inspiration that spreads like a celestial phenomenon, transcending borders, cultures, and generations."

**Review by brandon-moyer — APPROVED** [review]
apt should not be required, otherwise good

**Review by omrajpal — APPROVED** [review]
"The bad news is time flies. The good news is you're the pilot."

**Review by NoahRen25 — APPROVED** [review]

**Review by Jihong-Bae — APPROVED** [review]
apt should not be required, otherwise good

**Review by AlanJSudhan — APPROVED** [review]

**Pull request merged**
