### PR TITLE
Alan Carry ------> Made some rows not sortable

### PR DESCRIPTION
**Pull request by NoahRen25**
yes

### CODE REVIEW

**Review by Asingh11771 — APPROVED** [review]
Looks good

**Review by Jihong-Bae — APPROVED** [review]
Well done Alan. You're the MVP of the project. Approved By X-Bow30.

**Review by brandon-moyer — APPROVED** [review]
coaches sorts by id and not name, but otherwise looks good.

**Review by TortoiseRevenge — APPROVED** [review]
“There’s a huge trust. I see it all the time when people come up to me and say, ‘I don’t want you to let me down again.’ “ George W. Bush, Boston, Oct. 3, 2000

**Review by hraetz — APPROVED** [review]
slay

**Review by abby-winn — APPROVED** [review]

**Pull request merged**
