### PR TITLE
State Dropdown

### PR DESCRIPTION
**Pull request by brandon-moyer**
yes

### CODE REVIEW

**Review by omrajpal — APPROVED** [review]

**Review by abby-winn — APPROVED** [review]
"when merging, first we drag-- wait what do we drag" - _Noah Ren, 8th PM of Code The Way_

**Review by TortoiseRevenge — APPROVED** [review]
"I hear there's rumors on the Internets that we're going to have a draft." - President Dubya, presidential debate, St. Louis, Missouri, October 8, 2004

**Review by NoahRen25 — APPROVED** [review]

**Review by Asingh11771 — APPROVED** [review]
Looks good

**Review by hraetz — APPROVED** [review]
ok

**Review by Jihong-Bae — APPROVED** [review]
noah said its good

**Pull request merged**
