### PR TITLE
Student info/comm log reformat (scroll bars)

### PR DESCRIPTION
**Pull request by abby-winn**

### CODE REVIEW

**Review by omrajpal — APPROVED** [review]
"A real man isn't scared to broadcast his love for Olivia Rodrigo to his CTW team" - Proverbs 14:28

**Review by hraetz — APPROVED** [review]
okay
"Within the depths of the alpha male's soul burns an unquenchable fire, a flame that ignites with purpose, and fuels the pursuit of greatness. He is a force of nature, a behemoth of strength, whose footsteps resonate with the echoes of resilience and unwavering determination. In the face of adversity, he stands tall, unfazed by the tempests of life, for he knows that true strength lies not in the absence of challenges, but in the audacity to confront them head-on, to rise above the ordinary, and to carve his path with indomitable will."

**Review by brandon-moyer — APPROVED** [review]
Looks good.

**Review by Asingh11771 — APPROVED** [review]
Looks Good

**Review by TortoiseRevenge — APPROVED** [review]
"Sometimes when I sleep at night I think of (Dr. Seuss's) 'Hop on Pop." 
- George W. Bush, 43rd President of the United States of America

**Review by AlanJSudhan — APPROVED** [review]

**Review by NoahRen25 — APPROVED** [review]

**Pull request merged**
