### PR TITLE
phone validation w dashes for add and edit coach

### PR DESCRIPTION
**Pull request by omrajpal**

### CODE REVIEW

**Review by Asingh11771 — APPROVED** [review]
Looks Good

**Review by abby-winn — APPROVED** [review]
k

**Review by TortoiseRevenge — APPROVED** [review]

**Review by Jihong-Bae — APPROVED** [review]
i think it works

**Review by hraetz — APPROVED** [review]
nice

**Review by brandon-moyer — APPROVED** [review]
looks good

**Review by ryanosterberg — APPROVED** [review]
Q: Why don't dogs make good dancers?
A: Because they have two left feet!

Q: What happens when it rains cats and dogs?
A: You can step in a poodle!

Q: Why are dogs like phones?
A: Because they have collar IDs.

**Review by brandon-moyer — COMMENTED** [review]
https://www.youtube.com/watch?v=OfPRsXFU3Ak

**Pull request merged**
