### PR TITLE
Styling edit modals

### PR DESCRIPTION
**Pull request by hraetz**

### CODE REVIEW

**Review by omrajpal — APPROVED** [review]
"less is more" - 3 little pigs

**Review by Asingh11771 — APPROVED** [review]
Looks Good

"I like Eastern Europe as a whole because corruption is far more accessible"

**Review by ryanosterberg — APPROVED** [review]
“When I want your opinion, I’ll beat it out of you.” — Chuck Norris

**Review by AlanJSudhan — APPROVED** [review]
“Throw me to the wolves and I’ll return leading the pack.” - An Alpha Male

**Pull request merged**
