### PR TITLE
smallFixes SEVEN

### PR DESCRIPTION
**Pull request by hraetz**

### CODE REVIEW

**Review by Jihong-Bae — APPROVED** [review]
"In politics there are so many issues, sometimes boring. On tackling such a big-scale issue like climate change, it's got to be fun, it's got to be cool. It's got to be sexy too," - Shinjiro Koizumi [LINK P{LS WATCH PLSSSSSSSSSS](https://cdn.jwplayer.com/previews/SLPSHCGy)

**Review by TortoiseRevenge — APPROVED** [review]
"Our enemies are innovative and resourceful, and so are we. They never stop thinking about new ways to harm our country and our people, and neither do we." - George W. Bush

**Review by abby-winn — APPROVED** [review]
Improve your students’ math fact fluency with XtraMath's adaptive challenges and comprehensive reports. Loved by millions of teachers & parents since 2009.

**Review by Asingh11771 — APPROVED** [review]
"If you have to say or do something controversial, aim so that people will hate that they love it and not love that they hate it"

**Review by NoahRen25 — APPROVED** [review]

**Review by omrajpal — APPROVED** [review]
"He (adam) wasnt the hero this city (code teh way) deserved, but he was the hero this city needed." - batman (adam)

**Review by brandon-moyer — APPROVED** [review]

**Review by AlanJSudhan — APPROVED** [review]

**Pull request merged**
