### PR TITLE
changes on studentinfo/unassign coach

### PR DESCRIPTION
**Pull request by abby-winn**

### CODE REVIEW

**Review by Jihong-Bae — APPROVED** [review]
wp

**Review by ryanosterberg — APPROVED** [review]
I think things look good as long as Holly agrees with things.

**Review by Asingh11771 — APPROVED** [review]
Looks Good

**Review by omrajpal — APPROVED** [review]
shes back, watch yours...🤫

**Review by TortoiseRevenge — APPROVED** [review]

**Review by brandon-moyer — APPROVED** [review]
looks good

**Review by AlanJSudhan — APPROVED** [review]

**Review by NoahRen25 — APPROVED** [review]

**Pull request merged**
