### PR TITLE
Console Errors Done (Not incl DOMN & Double id)

### PR DESCRIPTION
**Pull request by NoahRen25**
yay

### CODE REVIEW

**Review by omrajpal — APPROVED** [review]
"Do not allow people to dim your shine because they are blinded. Tell them to put some sunglasses on."

**Review by Jihong-Bae — APPROVED** [review]
"In politics there are so many issues, sometimes boring. On tackling such a big-scale issue like climate change, it's got to be fun, it's got to be cool. It's got to be sexy too," [Koizumi ](https://www.independent.co.uk/climate-change/news/climate-change-sexy-fun-japan-environment-shinjiro-koizumi-a9115941.html)told a news conference in New York.

Noah your not fun, cool, sexy.

**Review by abby-winn — APPROVED** [review]
sieht gut, aber ich weiß nicht

**Review by TortoiseRevenge — APPROVED** [review]
“But that is not all. Oh no. That is not all!” - The Cat In The Hat (Dr. Seuss)

**Review by hraetz — APPROVED** [review]
I LOVE PROPTYPES
"The essence of an alpha male lies in the unwavering pursuit of excellence, the unrelenting commitment to personal growth, and the insatiable hunger to push beyond one's limits. He understands that true strength stems not from overpowering others, but from uplifting them, nurturing their potential, and fostering an environment where everyone can thrive. The alpha male leads with compassion, empathy, and a deep understanding of the power of unity. He stands as a pillar of inspiration, radiating confidence, and encouraging others to discover their own inner alpha, unlocking their unique abilities and igniting the flame of greatness that resides within."

**Review by AlanJSudhan — APPROVED** [review]

**Review by Asingh11771 — APPROVED** [review]
Looks Good

**Review by brandon-moyer — APPROVED** [review]
looks good

**Pull request merged**
