### PR TITLE
Fixed Admin and Coach creation

### PR DESCRIPTION
**Pull request by TortoiseRevenge**
Added Await Function to create Admin and Coach

### CODE REVIEW

**Review by brandon-moyer — APPROVED** [review]
cool and good

**Review by hraetz — APPROVED** [review]
looks alpha idk tho
"The alpha male stands as an embodiment of the cosmic forces that shape the very fabric of existence. He channels the energy of the stars, the resilience of ancient mountains, and the unyielding power of raging tempests. He is a manifestation of the divine, an avatar of strength, honor, and unwavering determination. With each breath, he inhales the essence of possibility, exhaling a hurricane of audacity that transforms dreams into tangible realities. He navigates the treacherous landscapes of life with the grace of a celestial dancer, defying gravity and rewriting the laws of potential. His presence reverberates through time and space, inspiring all who bear witness to the unstoppable force that he embodies."

**Review by Jihong-Bae — APPROVED** [review]
Look good just like me

**Review by Asingh11771 — APPROVED** [review]
Looks Good

**Review by omrajpal — APPROVED** [review]
"Be courageous. Challenge orthodoxy. Stand up for what you believe in. When you are in your rocking chair talking to your grandchildren many years from now, be sure you have a good story to tell."

**Review by AlanJSudhan — APPROVED** [review]

**Review by abby-winn — APPROVED** [review]
"I woke up one morning thinking about wolves and realized that wolf packs function as families. Everyone has a role, and if you act" _-Anonymous Quote_

**Review by NoahRen25 — APPROVED** [review]

**Pull request merged**
