### PR TITLE
SEL now uses dropdown

### PR DESCRIPTION
**Pull request by brandon-moyer**

### CODE REVIEW

**Review by Jihong-Bae — APPROVED** [review]
this code is not CFS

**Review by Asingh11771 — APPROVED** [review]
Looks good, aside from Jihong's comment

**Review by hraetz — APPROVED** [review]
"The alpha male is a paragon of fortitude, an embodiment of unwavering resolve. He faces life's trials with an unwavering belief in his abilities, armed with the conviction that failure is not an option. His spirit radiates an aura of invincibility, for he understands that true power lies not in overpowering others, but in conquering oneself. With each hurdle he overcomes, he transforms setbacks into stepping stones, fueling the fire of his passion, and ascending to extraordinary heights that leave the world in awe."

**Review by NoahRen25 — APPROVED** [review]

**Review by AlanJSudhan — APPROVED** [review]

**Review by TortoiseRevenge — APPROVED** [review]
"I'm telling you there's an enemy that would like to attack America, Americans, again. There just is. That's the reality of the world. And I wish him all the very best." – George W. Bush, Washington, D.C.; January 12, 2009

**Review by abby-winn — APPROVED** [review]
A horizontal stick is one metre long. Fifty ants are placed in random positions on the stick, pointing in random directions. The ants crawl head first along the stick, moving at one metre per minute. If an ant reaches the end of the stick, it falls off. If two ants meet, they both change direction. How long do you have to wait to be sure that all the ants have fallen off the stick?

**Review by omrajpal — APPROVED** [review]
“The true soldier fights not because he hates what is in front of him, but because he loves what is behind him.” 
― G.K. Chesterton

**Pull request merged**
