### PR TITLE
created new welcome page

### PR DESCRIPTION
**Pull request by omrajpal**

### CODE REVIEW

**Review by NoahRen25 — APPROVED** [review]

**Review by abby-winn — APPROVED** [review]
A commonly cited number is that approximately one in 10,000, or 0.01% of people, are thought to have perfect pitch.

**Review by Asingh11771 — APPROVED** [review]
gud

**Review by Jihong-Bae — APPROVED** [review]
image

**Review by hraetz — APPROVED** [review]
BEAUTIFUL

**Review by TortoiseRevenge — APPROVED** [review]
“Welcome to my hanging” George Dubya at the unveiling of his official presidential portrait, 6 December 2008

**Review by ryanosterberg — APPROVED** [review]
Looks good.

**Pull request merged**
