### PR TITLE
searchbar/add modal repos.

### PR DESCRIPTION
**Pull request by abby-winn**

### CODE REVIEW

**Review by NoahRen25 — APPROVED** [review]

**Review by hraetz — APPROVED** [review]
"An alpha male's legacy is not measured by the applause of the masses or the accumulation of worldly possessions. It is etched in the hearts of those he inspires, the lives he touches, and the positive impact he leaves behind. He understands that true greatness lies not in self-centered pursuits, but in the selfless service to others. He leads with integrity, guided by a moral compass that steers him towards righteousness, and he leaves a trail of goodness in his wake. His legacy is a symphony of love, compassion, and inspiration, resonating through time, and echoing in the hearts of generations yet to come."

**Review by TortoiseRevenge — APPROVED** [review]
"They misunderestimated me." - George W. Bush, Bentonville, Arkansas, November 6, 2000

**Review by Asingh11771 — APPROVED** [review]
“People who always want to be at convenient places won’t make a change at controversial places”

**Review by omrajpal — APPROVED** [review]
"You are in danger of living a life so comfortable and soft that you will die without ever realizing your true potential."

**Review by Jihong-Bae — APPROVED** [review]
잘하셨습니다

**Review by AlanJSudhan — APPROVED** [review]

**Pull request merged**
