### PR TITLE
big fix FOUR

### PR DESCRIPTION
**Pull request by hraetz**

### CODE REVIEW

**Review by abby-winn — CHANGES_REQUESTED** [review]
abysmal

**Review by TortoiseRevenge — CHANGES_REQUESTED** [review]
Please Fix the student details difference 

“Too many good docs are getting out of the business. Too many OB/GYNs aren’t able to practice their love with women all across the country.”- George Dubya Bush, Poplar Bluff, Mo., Sept. 6, 2004

**Review by Asingh11771 — APPROVED** [review]
aside from the box being the size of the content, the changes are fine

**Review by Jihong-Bae — APPROVED** [review]
image

**Pull request closed without merging**
