### PR TITLE
Modular Password Validation

### PR DESCRIPTION
**Pull request by Asingh11771**
"Submit beta male quotes instead of alpha male quotes"

-Brandon

### CODE REVIEW

**Review by TortoiseRevenge — APPROVED** [review]
"You work three jobs?… Uniquely American, isn't it? I mean, that is fantastic that you're doing that." —to a divorced mother of three,  George W. Bush, 43rd President of the United States, Omaha, Nebraska, February 4, 2005

**Comment by TortoiseRevenge** [comment]
"The most important thing is for us to find Osama bin Laden. It is our No. 1 priority, and we will not rest until we find him." —Washington, D.C., September 13, 2001 
 "I don't know where bin Laden is. I have no idea and really don't care. It's not that important. It's not our priority." —Washington, D.C., March 13, 2002

**Review by abby-winn — APPROVED** [review]
The Mandelbrot set is a two dimensional set with a relatively simple definition that exhibits great complexity, especially as it is magnified. It is popular for its aesthetic appeal and fractal structures. The set is defined in the complex plane as complex numbers c for which the function f(z)=z^2 + does not diverge to infinity when iterated starting at z=0.

**Review by NoahRen25 — APPROVED** [review]

**Review by hraetz — APPROVED** [review]
ok

**Review by AlanJSudhan — APPROVED** [review]

**Review by Jihong-Bae — APPROVED** [review]

**Review by omrajpal — APPROVED** [review]
16. “Life is not a matter of holding good cards, but of playing a poor hand well.” – [Robert Louis Stevenson](https://everydaypower.com/robert-louis-stevenson-quotes/)

**Pull request merged**
