### PR TITLE
Forgot and Reset Password Functionality

### PR DESCRIPTION
**Pull request by Asingh11771**

### CODE REVIEW

**Review by hraetz — APPROVED** [review]
i got the email

**Review by abby-winn — APPROVED** [review]

**Comment by ryanosterberg** [comment]
1.  Combine the welcome screen and the login screen
2. Hide the password and confirm password on the reset password page
3. Redirect to the login page after resetting the password
4. Thoughts on "forgot password" button placement/style

**Review by omrajpal — DISMISSED** [review]
they dont know you son

**Review by TortoiseRevenge — APPROVED** [review]

**Review by NoahRen25 — APPROVED** [review]

**Comment by ryanosterberg** [comment]
What do you get from a pampered cow? Spoiled milk!

What do you call a grizzly bear caught in the rain? A drizzly bear!

What's the most musical part of a chicken? The drumstick!

**Review by Jihong-Bae — APPROVED** [review]
k

**Pull request merged**
