### PR TITLE
Merge Student Info Icon allignment fix and onModalOpen refactoring into Dev

### PR DESCRIPTION
**Pull request by Asingh11771**

### CODE REVIEW

**Review by TortoiseRevenge — APPROVED** [review]
“You teach a child to read, and he or her will be able to pass a literacy test.” - George W. Bush, Townsend, Tenn., Feb. 21, 2001

**Review by hraetz — APPROVED** [review]
W

**Review by NoahRen25 — APPROVED** [review]

**Review by abby-winn — APPROVED** [review]
Physics is most interesting and most powerful when applied to general situations that involve more than a narrow set of physical principles. Newton’s laws of motion can also be integrated with other concepts that have been discussed previously in this text to solve problems of motion. For example, forces produce accelerations, a topic of kinematics, and hence the relevance of earlier chapters.

**Review by omrajpal — APPROVED** [review]
"When I'm in a slump, I comfort myself by saying if I believe in dinosaurs, then somewhere, they must be believing in me. And if they can believe in me, I can believe in me. Stay hard."

**Review by AlanJSudhan — APPROVED** [review]

**Review by Jihong-Bae — APPROVED** [review]

**Pull request merged**
