### PR TITLE
Reformatted modals/created default message for no careers found/other formatting

### PR DESCRIPTION
**Pull request by abby-winn**

### CODE REVIEW

**Review by Jihong-Bae — APPROVED** [review]

**Review by Asingh11771 — APPROVED** [review]
Looks Good

**Review by hraetz — APPROVED** [review]
ok

**Comment by hraetz** [comment]
"Before trying to render any component, you have to make sure that there is a LocalizationProvider upper in the React tree. This component receives your chosen [date library's adapter](https://mui.com/x/react-date-pickers/#date-library) (the doc uses AdapterDayjs which is based on [dayjs](https://day.js.org/)) and makes it accessible to all the Date and Time Pickers component using React context.

Each demonstration in the documentation has its own LocalizationProvider wrapper. This is not a pattern to reproduce. The reason is to keep examples atomic and functional—especially when running in a CodeSandbox.

The general recommendation is to declare the LocalizationProvider once, wrapping your entire application. Then, you don't need to repeat the boilerplate code for every Date and Time Picker in your application."

**Comment by TortoiseRevenge** [comment]
She didn't add me as a reviewer :(

“It’s important for us to explain to our nation that life is important. It’s not only life of babies, but it’s life of children living in, you know, the dark dungeons of the Internet.”- George W. Bush, 43rd President of the United States, Arlington Heights, Ill., Oct. 24, 2000

**Review by NoahRen25 — APPROVED** [review]

**Review by AlanJSudhan — APPROVED** [review]

**Review by omrajpal — APPROVED** [review]
“ Crazy people don't sit around wondering if they're nuts.”

**Review by brandon-moyer — APPROVED** [review]
Looks good

**Pull request merged**
