### PR TITLE
Making each comm log shorter 

### PR DESCRIPTION
**Pull request by NoahRen25**

### CODE REVIEW

**Review by Jihong-Bae — APPROVED** [review]
i think it works

**Review by hraetz — CHANGES_REQUESTED** [review]
ugly

**Review by TortoiseRevenge — CHANGES_REQUESTED** [review]
Please make it akin to the goals dropdown. Ideally, if it doesn't need it, it also shouldn't have a dropdown

**Review by Asingh11771 — CHANGES_REQUESTED** [review]
Dropdown arrows need to be put in the same position for each communication and the search bar and add button overlapping need to be fixed

**Review by brandon-moyer — APPROVED** [review]
re: Adam's request, to my knowledge it is not possible because Typography with noWrap does not have a way to track whether or not it is currently overflowing. That said, if it's centered, it will be all good.

**Review by omrajpal — APPROVED** [review]
be an uncommon man.

**Review by abby-winn — CHANGES_REQUESTED** [review]
it speaks for itself

**Review by hraetz — APPROVED** [review]
fixed my concern

**Review by omrajpal — APPROVED** [review]
"It may be satisfactory, but that's another word for mediocrity."

**Review by brandon-moyer — COMMENTED** [review]
in which Noah suffers from the quintessential front-end problem of centering stuff

**Review by abby-winn — APPROVED** [review]
fine ig

**Review by Asingh11771 — APPROVED** [review]
looks good now

**Review by TortoiseRevenge — APPROVED** [review]

**Pull request merged**
