### PR TITLE
date validation for add student, add goal, edit goal

### PR DESCRIPTION
**Pull request by omrajpal**

### CODE REVIEW

**Review by hraetz — APPROVED** [review]
idk

**Review by abby-winn — APPROVED** [review]
LaCroix or La Croix is an American brand of sparkling water that originated in La Crosse, Wisconsin, by G. Heileman Brewing Company and is now distributed by National Beverage Corporation. Their flavors include various fruits and fruit blends.

**Review by TortoiseRevenge — APPROVED** [review]
“There’s a huge trust. I see it all the time when people come up to me and say, ‘I don’t want you to let me down again.’ “ - George W. Bush, 43rd President of the United States, Boston, Oct. 3, 2000

**Review by NoahRen25 — APPROVED** [review]

**Review by Asingh11771 — APPROVED** [review]
Looks better

"Depression isn’t real. You feel sad, you move on. You will always be depressed if your life is depressing. Change it."

**Review by brandon-moyer — APPROVED** [review]
Looks good

**Pull request merged**
