### PR TITLE
Merge Careers into Develop

### PR DESCRIPTION
**Pull request by Asingh11771**

### CODE REVIEW

**Review by Jihong-Bae — APPROVED** [review]
approved by xbow30. just merge

**Review by NoahRen25 — APPROVED** [review]
no data val. but looks good

**Review by hraetz — APPROVED** [review]
"Shallow Men Believe In Luck Or In Circumstance. Strong Men Believe In Cause And Effect." ― Ralph Waldo Emerson

**Review by abby-winn — APPROVED** [review]
“Hard times create strong men, strong men create good times, good times create weak men, and weak men create hard times.” - _Those Who Remain, Michael Hopf_

**Review by AlanJSudhan — APPROVED** [review]

**Review by omrajpal — APPROVED** [review]

**Pull request merged**
