### PR TITLE
Fix various Data val bugs

### PR DESCRIPTION
**Pull request by Asingh11771**

### CODE REVIEW

**Review by abby-winn — APPROVED** [review]
"good morning                chatGPT"

**Review by hraetz — APPROVED** [review]
ok

**Review by TortoiseRevenge — APPROVED** [review]
“Well, I think if you say you’re going to do something and don’t do it, that’s trustworthiness.”- George W. Bush, CNN online chat, Aug. 30, 2000

**Review by NoahRen25 — APPROVED** [review]

**Review by Jihong-Bae — CHANGES_REQUESTED** [review]
🏹🏹🏹 xbow forever 🏹🏹🏹

WHEN THE FIELDS ARE NOT FILLLED ALL INCLUDING THE CHECK BOXES IT GIVES ERROR.

image

**Review by omrajpal — APPROVED** [review]
looking exquisite and marvelous

**Pull request merged**
