### PR TITLE
Merge career edit and delete into develop

### PR DESCRIPTION
**Pull request by Asingh11771**

### CODE REVIEW

**Review by hraetz — APPROVED** [review]
needs data val, idk tho

"I don't compete; I conquer. There can only be one alpha."

**Review by NoahRen25 — APPROVED** [review]

**Review by Jihong-Bae — APPROVED** [review]
approved by xbow30.

**Review by abby-winn — APPROVED** [review]
“When you wake up in the morning, tell yourself: the people I deal with today will be meddling, ungrateful, arrogant, dishonest, jealous and surly. They are like this because they can't tell good from evil. But I have seen the beauty of good, and the ugliness of evil, and have recognized that the wrongdoer has a nature related to my own - not of the same blood and birth, but the same mind, and possessing a share of the divine. And so none of them can hurt me. No one can implicate me in ugliness. Nor can I feel angry at my relative, or hate him. We were born to work together like feet, hands and eyes, like the two rows of teeth, upper and lower. To obstruct each other is unnatural. To feel anger at someone, to turn your back on him: these are unnatural.”
_―Marcus Aurelius, Meditations_

**Review by AlanJSudhan — APPROVED** [review]

**Review by omrajpal — APPROVED** [review]
the lion saw, the lion came, the lion conquered the jungle🦁🤴🏿

**Pull request merged**
