### PR TITLE
add goal, edit goal, add career, edit career, add comm modals don't change height

### PR DESCRIPTION
**Pull request by abby-winn**

### CODE REVIEW

**Review by Jihong-Bae — APPROVED** [review]
X-bow-Hate

**Review by TortoiseRevenge — APPROVED** [review]
"There's an old saying in Tennessee—I know it's in Texas, probably in Tennessee—that says, fool me once, shame on—shame on you. Fool me—you can't get fooled again." - Dubya, Nashville, Tenn., September 17, 2002

**Review by Asingh11771 — APPROVED** [review]
Looks Good

**Comment by ryanosterberg** [comment]
The search bar is broken!!!!!

!dlroW olleH

**Pull request merged**
