### PR TITLE
No deactivate self

### PR DESCRIPTION
**Pull request by hraetz**

### CODE REVIEW

**Review by Jihong-Bae — APPROVED** [review]
ye

**Review by NoahRen25 — APPROVED** [review]

**Review by abby-winn — APPROVED** [review]
“I have not failed. I’ve just found 10,000 ways that won’t work.”  _- Holly_

**Review by ryanosterberg — APPROVED** [review]
What do you call an alligator who is a thief? A crookodile

What do you get when you cross a chicken with a cow? Roost beef!

What do you call an illegally parked frog? Toad!

**Review by TortoiseRevenge — APPROVED** [review]

**Review by Asingh11771 — APPROVED** [review]
Looks Good

**Review by omrajpal — APPROVED** [review]
"They all see the gold medal, but they never see the iron it took to make it" - Anononymous iykyk june 2023

**Review by brandon-moyer — APPROVED** [review]
Looks good

**Review by AlanJSudhan — APPROVED** [review]

**Pull request merged**
