### PR TITLE
DynamicTable to dev

### PR DESCRIPTION
**Pull request by TortoiseRevenge**

### CODE REVIEW

**Review by Asingh11771 — APPROVED** [review]
Aside from certain Eslint issues, the dynamic table components in this branch are clean and work well.

**Review by brandon-moyer — APPROVED** [review]
ESLint issues, but otherwise looks good to merge.

**Review by hraetz — APPROVED** [review]
Other than todal, looks good!

**Review by AlanJSudhan — APPROVED** [review]

**Review by Jihong-Bae — APPROVED** [review]
awesome!!!

**Pull request merged**
