### PR TITLE
big fixes FOUR

### PR DESCRIPTION
**Pull request by hraetz**

### CODE REVIEW

**Review by abby-winn — CHANGES_REQUESTED** [review]
com log longgggggggggggg also shifty student details tab

 “Failure should be our teacher, not our undertaker. Failure is delay, not defeat. It is a temporary detour, not a dead end. Failure is something we can avoid only by saying nothing, doing nothing, and being nothing.” _- Denis Waitley_

**Review by brandon-moyer — CHANGES_REQUESTED** [review]
Goal and communication stretching is too big of a bug to put this into dev

**Comment by hraetz** [comment]
fixed the problem :sunglasses:

**Review by TortoiseRevenge — APPROVED** [review]

**Review by ryanosterberg — APPROVED** [review]
What happens to a toad's car when it breaks down? It gets toad away.

What do cats have for breakfast? Mice Crispies!

A pony went to see the doctor, because it couldn't speak. "I know what's wrong," said the doctor. "You're a little horse!"

**Review by brandon-moyer — APPROVED** [review]
Approved, also has Aniket's approval because he's busy testing

**Review by omrajpal — APPROVED** [review]
anybody could do it, just not like holly👀

**Review by Jihong-Bae — APPROVED** [review]
ok

**Pull request merged**
