### PR TITLE
smallFixes EEIIGGHHTT

### PR DESCRIPTION
**Pull request by hraetz**

### CODE REVIEW

**Review by Jihong-Bae — APPROVED** [review]

**Review by abby-winn — APPROVED** [review]

**Review by TortoiseRevenge — APPROVED** [review]
"We spent a lot of time talking about Africa, as we should. Africa is a nation that suffers from incredible disease." - George W. Bush, 43rd President of the United States, Gothenburg, Sweden, June 14, 2001

**Comment by abby-winn** [comment]
“Laziness is a secret ingredient that goes into failure. But it's only kept a secret from the person who fails.”

**Review by Asingh11771 — APPROVED** [review]
Looks good

"Work sets you free"

**Comment by TortoiseRevenge** [comment]
"Families is where our nation finds hope, where wings take dream." - George W. Bush, LaCrosse, Wisconsin, October 18, 2000

**Review by omrajpal — APPROVED** [review]
"Never let someone else tell you your limits. If someone says you can't work on your presentation, go work on that presentation and make it better than they could ever imagine."

**Comment by TortoiseRevenge** [comment]
"I am here to make an announcement that this Thursday, ticket counters and airplanes will fly out of Ronald Reagan Airport." —Washington, D.C., October 3, 2001

**Review by brandon-moyer — APPROVED** [review]
play 1.e4 e5 2.Ke2!! Ke7!! to be a true alpha male

**Comment by abby-winn** [comment]
Linear algebra is the branch of mathematics concerning linear equations such as: In three-dimensional Euclidean space, these three planes represent solutions to ...

**Comment by TortoiseRevenge** [comment]
"See, in my line of work you got to keep repeating things over and over and over again for the truth to sink in, to kind of catapult the propaganda." —Greece, New York, May 24, 2005

**Review by NoahRen25 — APPROVED** [review]

**Comment by abby-winn** [comment]
PAWN TO e4

**Review by AlanJSudhan — APPROVED** [review]

**Pull request merged**
