### PR TITLE
Merge table sizing, removed phone number from search, and capitaization validation

### PR DESCRIPTION
**Pull request by Asingh11771**

### CODE REVIEW

**Review by omrajpal — APPROVED** [review]
;(

**Review by abby-winn — APPROVED** [review]
Run Curl commands directly in your browser and see the results online. Test APIs, websites, and web services. Save, share, and collaborate on your Curl commands online. Learn Curl with an extensive and handcrafted database of Curl examples. No browser plugins or additional desktop software are needed for using the ReqBin Online Curl Client. It's free.

**Review by hraetz — APPROVED** [review]
okay

**Review by TortoiseRevenge — APPROVED** [review]
One of the great things about books is sometimes there are some fantastic pictures.” - George W. Bush, 43rd President of the United States, U.S. News & World Report, Jan. 3, 2000

**Review by NoahRen25 — APPROVED** [review]

**Review by Jihong-Bae — APPROVED** [review]
image

**Pull request merged**
