### PR TITLE
Date Fix + General Code Clean Up

### PR DESCRIPTION
**Pull request by AlanJSudhan**

### CODE REVIEW

**Review by TortoiseRevenge — APPROVED** [review]
“And there is distrust in Washington. I am surprised, frankly, at the amount of distrust that exists in this town. And I’m sorry it’s the case, and I’ll work hard to try to elevate it.”- George W. Bush speaking on National Public Radio, Jan. 29, 2007

**Review by Jihong-Bae — APPROVED** [review]
- can't select coach
- date picker margin bot 2px

**Review by hraetz — APPROVED** [review]
okay

**Review by abby-winn — APPROVED** [review]
In the first law, an object will not change its motion unless a force acts on it. In the second law, the force on an object is equal to its mass times its acceleration. In the third law, when two objects interact, they apply forces to each other of equal magnitude and opposite direction.

**Review by NoahRen25 — APPROVED** [review]

**Review by Asingh11771 — APPROVED** [review]
Looks Good

**Review by omrajpal — APPROVED** [review]
"Be more than motivated, be more than driven, become literally obsessed to the point where people think you're fucking nuts."

**Review by brandon-moyer — APPROVED** [review]
Looks good

**Pull request merged**
