### PR TITLE
cant access swagger, "no goals found", "no communications found"

### PR DESCRIPTION
**Pull request by abby-winn**

### CODE REVIEW

**Review by hraetz — APPROVED** [review]
looks mid (except the part i did thats super awesome and cool)

**Review by brandon-moyer — APPROVED** [review]
https://youtu.be/oGEIdd-7gHw

**Review by Asingh11771 — APPROVED** [review]
gud

**Review by Jihong-Bae — APPROVED** [review]
🏹🏹🏹xbow forever🏹🏹🏹

**Review by TortoiseRevenge — APPROVED** [review]
“I know how hard it is for you to put food on your family.”- George Dubya, Greater Nashua, N.H., Chamber of Commerce, Jan. 27, 2000

**Review by NoahRen25 — APPROVED** [review]

**Review by omrajpal — COMMENTED** [review]
idk

**Pull request merged**
