### PR TITLE
ConsoleErrors

### PR DESCRIPTION
**Pull request by NoahRen25**
yes

### CODE REVIEW

**Review by Jihong-Bae — APPROVED** [review]
good

**Review by omrajpal — APPROVED** [review]
"There is no more time to waste. Hours and days evaporate like creeks in the desert. That’s why it’s okay to be cruel to yourself as long as you realize you’re doing it to become better."

"Be more than motivated, be more than driven, become literally obsessed to the point where people think you're fucking nuts."

**Review by brandon-moyer — APPROVED** [review]
Looks good.

**Review by Asingh11771 — APPROVED** [review]
Aside from Validate DOM issue, Looks good

**Review by hraetz — APPROVED** [review]
ok

**Review by abby-winn — APPROVED** [review]
F = ma, or net force is equal to mass times acceleration. A larger net force acting on an object causes a larger acceleration, and objects with larger mass require more force to accelerate.

**Pull request merged**
