### PR TITLE
onCancel switch coach model, now shows correct values

### PR DESCRIPTION
**Pull request by Jihong-Bae**
onCancel switch coach model, now shows correct values

Issue: cancel button in assign coach doesn't reset entry

### CODE REVIEW

**Review by Asingh11771 — APPROVED** [review]
good

**Review by brandon-moyer — APPROVED** [review]
https://www.youtube.com/watch?v=5pUSX9kvARQ

**Review by hraetz — APPROVED** [review]
uhhhh

**Review by abby-winn — APPROVED** [review]
i do not trust this at all

**Review by omrajpal — APPROVED** [review]
great changes

**Review by TortoiseRevenge — COMMENTED** [review]
Watch this Pull Request - George Dubya, today

**Comment by Jihong-Bae** [comment]
> Watch this Pull Request - George Dubya, today

🏹

**Pull request merged**
