### PR TITLE
New formatting on student details page

### PR DESCRIPTION
**Pull request by abby-winn**

### CODE REVIEW

**Review by hraetz — APPROVED** [review]
c'est d'accord, mais je ne sais pas
"In the grand tapestry of existence, the alpha male assumes his role as a sculptor of destiny, fearlessly shaping his own path and leaving an indelible mark on the world. He possesses an unquenchable thirst for knowledge, forever seeking to expand his horizons, challenge his limits, and surpass his previous accomplishments. The alpha male understands that true strength lies not in brute force, but in emotional intelligence, empathy, and the ability to lead with grace. With every setback, he embraces resilience, turning obstacles into stepping stones, and failures into lessons that propel him ever closer to his aspirations. His journey is not for personal glory, but a testament to the boundless heights humanity can reach when guided by unwavering determination and an unwavering commitment to excellence."

**Review by NoahRen25 — APPROVED** [review]

**Review by TortoiseRevenge — APPROVED** [review]
“And this mess is so big 
And so deep and so tall, 
We cannot pick it up. 
There is no way at all!”

**Review by AlanJSudhan — APPROVED** [review]

**Review by Asingh11771 — APPROVED** [review]
Looks Good

**Review by omrajpal — APPROVED** [review]
If you can't amaze them with your brilliance, dazzle them with your stupidity!

**Review by Jihong-Bae — APPROVED** [review]
Dojokivic > alcaraz

**Comment by omrajpal** [comment]
"I am not afraid of an army of lions led by a sheep; I am afraid of an army of sheep led by a lion." - Om

**Pull request merged**
