### PR TITLE
Inactive table resize and scrollable

### PR DESCRIPTION
**Pull request by omrajpal**

### CODE REVIEW

**Review by NoahRen25 — APPROVED** [review]
The era of procrastination, of half-measures, of soothing and baffling expedients, of delays is coming to its close. In its place we are entering a period of consequences. - Winston Churchill

**Review by TortoiseRevenge — APPROVED** [review]
“But I like to be here. Oh, I like it a lot!”

**Review by Jihong-Bae — APPROVED** [review]
I want the sx props for max height to be 40% not 510.

not cool, fun, sexy. - koizumi shinjiro

**Review by abby-winn — APPROVED** [review]
"It was loath to believe, it cannot now bring itself to believe, that these acts, so absolutely contrary to the rules, the practices, and the spirit of modern warfare, could have the countenance or sanction of that great Government (Woodrow Wilson Report 34).”

**Review by hraetz — APPROVED** [review]
okay







 "The alpha male is not defined by physical prowess alone, but by the depth of his character and the unwavering values that guide his every action. He embodies the spirit of a true leader, inspiring others through his authenticity, empathy, and ability to unite diverse minds towards a common purpose. The alpha male recognizes that true power lies in empowering others, fostering a collaborative environment that unleashes the collective genius of the team. He understands that success is not measured by individual achievements but by the collective growth and achievements of those around him. With unwavering integrity and an unshakeable moral compass, the alpha male becomes a beacon of light, guiding others towards greatness and leaving an enduring legacy that transcends time."

**Review by ryanosterberg — APPROVED** [review]
Looks good.

**Review by AlanJSudhan — APPROVED** [review]

**Comment by ryanosterberg** [comment]
The frog does not drink up the pond in which he lives.

**Comment by omrajpal** [comment]
"I am not afraid of an army of lions led by a sheep; I am afraid of an army of sheep led by a lion." - Om

**Review by brandon-moyer — APPROVED** [review]
aren't all these quotes kind of unprofessional? anyways, loosk good

**Review by Asingh11771 — APPROVED** [review]
Looks Good

**Pull request merged**
