### PR TITLE
fix: remove login from Navbar

### PR DESCRIPTION
**Pull request by Asingh11771**

### CODE REVIEW

**Review by TortoiseRevenge — APPROVED** [review]

**Review by brandon-moyer — APPROVED** [review]
Looks good

**Review by hraetz — APPROVED** [review]
perf

**Review by NoahRen25 — APPROVED** [review]

**Review by Jihong-Bae — APPROVED** [review]
123456789

**Review by abby-winn — APPROVED** [review]
“He was a Frenchman, a melancholy-looking man. His aspect was that of one who has been looking for the leak in a gas pipe with a lighted candle.” _― P.G. Wodehouse_

**Review by AlanJSudhan — APPROVED** [review]

**Pull request merged**
