### PR TITLE
Validation Fixes

### PR DESCRIPTION
**Pull request by hraetz**

### CODE REVIEW

**Review by NoahRen25 — APPROVED** [review]

**Review by brandon-moyer — APPROVED** [review]
Looks good

**Review by abby-winn — APPROVED** [review]
great job. "Success is not final; failure is not fatal: It is the courage to continue that counts." -Winston S. Churchill

**Review by Jihong-Bae — APPROVED** [review]
Good stuff, Approved by xbow30.

**Review by Asingh11771 — APPROVED** [review]
So far looks good

**Review by omrajpal — APPROVED** [review]

**Review by AlanJSudhan — APPROVED** [review]

**Pull request merged**
