### PR TITLE
merging activate admin into dev

### PR DESCRIPTION
**Pull request by omrajpal**

### CODE REVIEW

**Review by Asingh11771 — APPROVED** [review]
Looks good

**Review by brandon-moyer — APPROVED** [review]
Looks good.

**Review by hraetz — APPROVED** [review]
Other than email, great!

**Review by Jihong-Bae — APPROVED** [review]
cool

**Review by hraetz — APPROVED** [review]
Good

**Review by Jihong-Bae — APPROVED** [review]
good

**Review by TortoiseRevenge — APPROVED** [review]

**Review by Asingh11771 — APPROVED** [review]
looks good

**Review by brandon-moyer — COMMENTED** [review]
Looking good 2: electric boogaloo

**Pull request merged**
