### PR TITLE
Student Info: Edit and Get Information

### PR DESCRIPTION
**Pull request by abby-winn**

### CODE REVIEW

**Review by omrajpal — APPROVED** [review]

**Review by Jihong-Bae — APPROVED** [review]
working well, approved by xbow30

**Review by brandon-moyer — APPROVED** [review]
In the future, add validation to prevent setting birthday to the future. DatePicker has functionality for that.

**Review by Asingh11771 — APPROVED** [review]
Aside from validation, everything is good.

**Review by hraetz — APPROVED** [review]
Blood, sweat, & respect. The first two you give. Last one you earn. – Dwayne “The Rock” Johnson

**Review by AlanJSudhan — APPROVED** [review]

**Review by NoahRen25 — APPROVED** [review]
dk if we want apt. #, otherwise looks great

**Review by ryanosterberg — APPROVED** [review]
Alpha males do not follow the crowd.

**Pull request merged**
