### PR TITLE
Inactive table for coach and admin

### PR DESCRIPTION
**Pull request by omrajpal**

### CODE REVIEW

**Review by brandon-moyer — APPROVED** [review]
insert whistling here

**Review by hraetz — APPROVED** [review]
ok

**Review by TortoiseRevenge — APPROVED** [review]

**Review by Jihong-Bae — APPROVED** [review]
Approved by Jihong Bae, Thank you Chat GPT for sponsoring my reviews.

**Review by AlanJSudhan — APPROVED** [review]
Seems legit

**Review by abby-winn — APPROVED** [review]

**Pull request merged**
