### PR TITLE
Communications Log Merge

### PR DESCRIPTION
**Pull request by TortoiseRevenge**

### CODE REVIEW

**Review by hraetz — APPROVED** [review]
Other than the temporary hardcoded sizing in communication-log, looks good!

**Review by Asingh11771 — APPROVED** [review]
Aside from the dropdowns in the modals for Goals and Careers, It is good to merge.

**Review by brandon-moyer — APPROVED** [review]
Components like modal-component.js are a bit too large, and ideally comments should be added to whereever the L2C crew might change things around to their needs (e.g. labelArray and headerArray in student-details). Also, percentage-based sizing to make it more suitable to different viewport sizes would be ideal. Otherwise, it's suitable to merge.

**Review by Jihong-Bae — APPROVED** [review]
i don't like the icon sections, switch it up to better one. 
also, the hovers of the icons are kind of not aligned

**Review by AlanJSudhan — APPROVED** [review]

**Pull request merged**
