### PR TITLE
Merge Various Data Validation Fixes into Develop

### PR DESCRIPTION
**Pull request by Asingh11771**

### CODE REVIEW

**Review by Jihong-Bae — APPROVED** [review]
i am proud of you

**Review by omrajpal — APPROVED** [review]

**Review by abby-winn — APPROVED** [review]
sehr schlecht, du hast mich wütend gemacht

**Review by AlanJSudhan — APPROVED** [review]

**Review by TortoiseRevenge — APPROVED** [review]
“Describe him? That’s hard, I don’t know if I can.”

**Review by hraetz — APPROVED** [review]
"As an alpha male in Christ, I find my strength in Him. I draw upon His grace, His wisdom, and His love to navigate life's challenges with confidence and resilience."

**Review by NoahRen25 — APPROVED** [review]

**Pull request merged**
