### PR TITLE
serchbar isnow fully clicking and searach bar indent

### PR DESCRIPTION
**Pull request by Jihong-Bae**
just appprove idc

### CODE REVIEW

**Review by omrajpal — APPROVED** [review]
real men cant spell. stay hard

**Review by NoahRen25 — APPROVED** [review]

**Review by Asingh11771 — APPROVED** [review]
looks goodd

**Review by hraetz — APPROVED** [review]
SEARACH BAR IS JOEY APPROVED

**Comment by hraetz** [comment]
image_2023-07-19_101711328-modified

**Review by abby-winn — APPROVED** [review]
gud serchbaaer 10/10

**Review by brandon-moyer — APPROVED** [review]
https://www.youtube.com/watch?v=LiYqTcaq_Zo

**Review by TortoiseRevenge — APPROVED** [review]
"Tribal sovereignty means that; it's sovereign. I mean, you're a—you've been given sovereignty, and you're viewed as a sovereign entity. And therefore the relationship between the federal government and tribes is one between sovereign entities." —Washington, D.C., August 6, 2004

**Pull request merged**
