### PR TITLE
Add student, add coach, edit student info, edit parent info modals don't change height/validation altered

### PR DESCRIPTION
**Pull request by abby-winn**

### CODE REVIEW

**Review by omrajpal — APPROVED** [review]
they call me dora the way my bag talk

**Review by Jihong-Bae — APPROVED** [review]
"Embrace the boundless horizon of knowledge, for within its depths, countless wonders await curious minds to unveil." - brother gpt

**Review by Asingh11771 — APPROVED** [review]
Looks Good

**Review by NoahRen25 — APPROVED** [review]

**Review by TortoiseRevenge — APPROVED** [review]
"I know that human beings and fish can coexist peacefully." - George Dubya, Saginaw Michigan, September 29, 2000, while attempting to reassure the business community that he does not support tearing down dams.

**Review by ryanosterberg — APPROVED** [review]
Phone Number validation is broken for add coach...but I guess this was not your fault.

**Review by hraetz — APPROVED** [review]
genuinely terrible.

**Pull request merged**
