### PR TITLE
Edit goal refresh fix into development

### PR DESCRIPTION
**Pull request by brandon-moyer**

### CODE REVIEW

**Review by NoahRen25 — APPROVED** [review]

**Review by hraetz — APPROVED** [review]
Looks good!

**Review by Asingh11771 — APPROVED** [review]
Looks Good

**Review by Jihong-Bae — APPROVED** [review]
Approved, but you shuld make "Enter" also same the edit details and return to the page. you know. (@^@)

**Review by abby-winn — APPROVED** [review]
nice 👍

**Pull request merged**
