### PR TITLE
Goal formatting into dev

### PR DESCRIPTION
**Pull request by abby-winn**

### CODE REVIEW

**Review by Asingh11771 — APPROVED** [review]
looks good, only thing remaining is scrollbar and add button being a plus

**Review by brandon-moyer — APPROVED** [review]
looks good, reviewed w/ aniket

**Review by hraetz — APPROVED** [review]
looks good but idk tho

"The essence of true masculinity lies not merely in physical prowess or dominance, but in the unwavering commitment to self-mastery, the relentless pursuit of excellence, and the boundless reservoirs of resilience that define the alpha male. He walks with unwavering confidence, radiating an aura of purpose that inspires and captivates."

**Review by NoahRen25 — APPROVED** [review]

**Review by Jihong-Bae — APPROVED** [review]
do it

**Review by omrajpal — APPROVED** [review]
Hard times don't last, but hard men do.

**Pull request merged**
